### PR TITLE
Adding a Creator's Update column

### PR DESCRIPTION
**Pull request by kelkarajay**

### CODE REVIEW

**Comment by davatron5000** [comment]
I’m traveling today but I’ll take a look at this soon. Thank you!

________________________________

**Comment by RichardSlater** [comment]
Poke @davatron5000 ... would be good to see this added :)

**Comment by davatron5000** [comment]
Let's do it! WowooOOo

**Comment by RichardSlater** [comment]
:-) thank you

**Comment by davatron5000** [comment]
🤔 Hm. This maybe doesn't render how I thought it would.

**Pull request merged**
